version: "3"
services:
  core:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/opt/treehole
    links:
      - database
  database:
    image: postgres:11.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
